function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 12-Aug-2026 08:58:07

% Create figure
figure1 = figure('Name','Prueba de sensores del TCLab');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'MarkerSize',4,'LineWidth',1.2);
set(plot1(1),'DisplayName','T_1','Marker','o');
set(plot1(2),'DisplayName','T_2','Marker','square');

% Create ylabel
ylabel('Temperatura (°C)');

% Create xlabel
xlabel('Tiempo (s)');

% Create title
title('Temperaturas con Q_1=Q_2=0');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

