%% Validacion comparativa del modelo MIL del TCLab
% Compara tres implementaciones del PI SIMC/IMC en una sola simulacion:
%   1. PI ideal, sin saturacion.
%   2. PI con saturacion externa, sin anti-windup.
%   3. PI con saturacion interna y anti-windup por clamping.
%
% Antes de ejecutar este script, el modelo de Simulink debe generar las
% siguientes variables mediante bloques To Workspace en formato Timeseries:
%
%   T1_ideal_sim       Qcmd_ideal_sim
%   T1_sinAW_sim       Qcmd_sinAW_sim       Q1_sinAW_sim
%   T1_conAW_sim                              Q1_conAW_sim
%
% Tambien deben estar disponibles T_ref, T_amb, Q_min, Q_max, T_max,
% ts_max y OS_max, definidos en init_TCLab_SIMC.m.

%% Comprobacion de variables necesarias

variables_necesarias = { ...
    'T1_ideal_sim', ...
    'Qcmd_ideal_sim', ...
    'T1_sinAW_sim', ...
    'Qcmd_sinAW_sim', ...
    'Q1_sinAW_sim', ...
    'T1_conAW_sim', ...
    'Q1_conAW_sim', ...
    'T_ref', ...
    'T_amb', ...
    'Q_min', ...
    'Q_max', ...
    'T_max', ...
    'ts_max', ...
    'OS_max'};

variables_faltantes = variables_necesarias( ...
    ~cellfun(@(nombre) evalin('base', ...
    sprintf("exist('%s','var')", nombre)), variables_necesarias));

if ~isempty(variables_faltantes)
    error('Faltan las siguientes variables: %s', ...
        strjoin(variables_faltantes, ', '));
end

%% Calculo de metricas

% En el caso ideal, la potencia solicitada y la aplicada son iguales.
metricas_ideal = calcularMetricasSimulink( ...
    T1_ideal_sim, ...
    Qcmd_ideal_sim, ...
    Qcmd_ideal_sim, ...
    T_ref, T_amb, Q_min, Q_max);

metricas_sinAW = calcularMetricasSimulink( ...
    T1_sinAW_sim, ...
    Qcmd_sinAW_sim, ...
    Q1_sinAW_sim, ...
    T_ref, T_amb, Q_min, Q_max);

% El bloque Discrete PID Controller con limites internos entrega la salida
% ya saturada. Por eso Qcmd no esta disponible en este caso y se pasa [].
metricas_conAW = calcularMetricasSimulink( ...
    T1_conAW_sim, ...
    [], ...
    Q1_conAW_sim, ...
    T_ref, T_amb, Q_min, Q_max);

%% Tabla comparativa

Caso = [ ...
    "PI ideal"; ...
    "Saturacion sin AW"; ...
    "Saturacion con AW"];

TiempoSubida_s = [ ...
    metricas_ideal.RiseTime; ...
    metricas_sinAW.RiseTime; ...
    metricas_conAW.RiseTime];

TiempoEstablecimiento_s = [ ...
    metricas_ideal.SettlingTime; ...
    metricas_sinAW.SettlingTime; ...
    metricas_conAW.SettlingTime];

Sobreimpulso_pct = [ ...
    metricas_ideal.Overshoot; ...
    metricas_sinAW.Overshoot; ...
    metricas_conAW.Overshoot];

ErrorEstacionario_degC = [ ...
    metricas_ideal.ErrorEstacionario; ...
    metricas_sinAW.ErrorEstacionario; ...
    metricas_conAW.ErrorEstacionario];

TemperaturaMaxima_degC = [ ...
    metricas_ideal.TemperaturaMaxima; ...
    metricas_sinAW.TemperaturaMaxima; ...
    metricas_conAW.TemperaturaMaxima];

PotenciaMinima_pct = [ ...
    metricas_ideal.PotenciaMinima; ...
    metricas_sinAW.PotenciaMinima; ...
    metricas_conAW.PotenciaMinima];

PotenciaMaxima_pct = [ ...
    metricas_ideal.PotenciaMaxima; ...
    metricas_sinAW.PotenciaMaxima; ...
    metricas_conAW.PotenciaMaxima];

TiempoQcmdFueraRango_s = [ ...
    metricas_ideal.TiempoQcmdFueraRango; ...
    metricas_sinAW.TiempoQcmdFueraRango; ...
    metricas_conAW.TiempoQcmdFueraRango];

resultados_SIMC = table( ...
    Caso, ...
    TiempoSubida_s, ...
    TiempoEstablecimiento_s, ...
    Sobreimpulso_pct, ...
    ErrorEstacionario_degC, ...
    TemperaturaMaxima_degC, ...
    PotenciaMinima_pct, ...
    PotenciaMaxima_pct, ...
    TiempoQcmdFueraRango_s);

fprintf('\nCOMPARACION DE RESULTADOS EN SIMULINK\n');
fprintf('====================================================\n');
disp(resultados_SIMC);

fprintf(['Nota: TiempoQcmdFueraRango_s es NaN para el caso con ', ...
    'anti-windup porque el bloque PID no expone su senal interna ', ...
    'anterior a la saturacion.\n']);

%% Verificacion de requisitos del controlador con anti-windup

cumplimiento_conAW = table( ...
    metricas_conAW.SettlingTime <= ts_max, ...
    metricas_conAW.Overshoot <= OS_max, ...
    metricas_conAW.PotenciaMinima >= Q_min && ...
        metricas_conAW.PotenciaMaxima <= Q_max, ...
    metricas_conAW.TemperaturaMaxima <= T_max, ...
    'VariableNames', { ...
        'CumpleTiempoEstablecimiento', ...
        'CumpleSobreimpulso', ...
        'CumpleLimitesPotencia', ...
        'CumpleLimiteTemperatura'});

fprintf('\nCUMPLIMIENTO CON SATURACION Y ANTI-WINDUP\n');
fprintf('====================================================\n');
disp(cumplimiento_conAW);

%% Graficas comparativas

[t_T_ideal, T_ideal] = extraerTimeseries( ...
    T1_ideal_sim, 'T1_ideal_sim');

[t_T_sinAW, T_sinAW] = extraerTimeseries( ...
    T1_sinAW_sim, 'T1_sinAW_sim');

[t_T_conAW, T_conAW] = extraerTimeseries( ...
    T1_conAW_sim, 'T1_conAW_sim');

[t_Q_ideal, Q_ideal] = extraerTimeseries( ...
    Qcmd_ideal_sim, 'Qcmd_ideal_sim');

[t_Qcmd_sinAW, Qcmd_sinAW] = extraerTimeseries( ...
    Qcmd_sinAW_sim, 'Qcmd_sinAW_sim');

[t_Q1_sinAW, Q1_sinAW] = extraerTimeseries( ...
    Q1_sinAW_sim, 'Q1_sinAW_sim');

[t_Q1_conAW, Q1_conAW] = extraerTimeseries( ...
    Q1_conAW_sim, 'Q1_conAW_sim');

figure('Name', 'Comparacion PI SIMC/IMC', 'Color', 'w');
tiledlayout(3, 1, 'TileSpacing', 'compact', 'Padding', 'compact');

nexttile;
plot(t_T_ideal, T_ideal, 'LineWidth', 1.4, ...
    'DisplayName', 'PI ideal');
hold on;
plot(t_T_sinAW, T_sinAW, 'LineWidth', 1.4, ...
    'DisplayName', 'Saturacion sin AW');
plot(t_T_conAW, T_conAW, 'LineWidth', 1.4, ...
    'DisplayName', 'Saturacion con AW');
yline(T_ref, ':k', 'Referencia', 'HandleVisibility', 'off');
grid on;
ylabel('T_1 [degC]');
legend('Location', 'best');
title('Temperatura');

nexttile;
plot(t_Q_ideal, Q_ideal, 'LineWidth', 1.4, ...
    'DisplayName', 'PI ideal');
hold on;
plot(t_Q1_sinAW, Q1_sinAW, 'LineWidth', 1.4, ...
    'DisplayName', 'Saturacion sin AW');
plot(t_Q1_conAW, Q1_conAW, 'LineWidth', 1.4, ...
    'DisplayName', 'Saturacion con AW');
yline(Q_max, ':r', 'Limite superior', 'HandleVisibility', 'off');
yline(Q_min, ':k', 'Limite inferior', 'HandleVisibility', 'off');
grid on;
ylabel('Q_1 [%]');
legend('Location', 'best');
title('Potencia aplicada');

nexttile;
plot(t_Qcmd_sinAW, Qcmd_sinAW, 'LineWidth', 1.4, ...
    'DisplayName', 'Q_{cmd}');
hold on;
plot(t_Q1_sinAW, Q1_sinAW, '--', 'LineWidth', 1.4, ...
    'DisplayName', 'Q_1');
yline(Q_max, ':r', 'Limite superior', 'HandleVisibility', 'off');
yline(Q_min, ':k', 'Limite inferior', 'HandleVisibility', 'off');
grid on;
xlabel('Tiempo [s]');
ylabel('Potencia [%]');
legend('Location', 'best');
title('Windup: saturacion sin anti-windup');

%% Funciones locales

function metricas = calcularMetricasSimulink( ...
    T1_ts, Qcmd_ts, Q1_ts, T_ref, T_amb, Q_min, Q_max)

    [t_T1, T1] = extraerTimeseries(T1_ts, 'temperatura');
    [~, Q1] = extraerTimeseries(Q1_ts, 'potencia aplicada');

    DeltaT1 = T1 - T_amb;
    DeltaT_ref = T_ref - T_amb;

    info = stepinfo( ...
        DeltaT1, ...
        t_T1, ...
        DeltaT_ref, ...
        'SettlingTimeThreshold', 0.02);

    indices_finales = t_T1 >= t_T1(end) - 60;
    error_estacionario = T_ref - mean(T1(indices_finales));

    if isempty(Qcmd_ts)
        tiempo_Qcmd_fuera_rango = NaN;
    else
        [t_Qcmd, Qcmd] = extraerTimeseries(Qcmd_ts, 'comando PI');

        if numel(t_Qcmd) < 2
            tiempo_Qcmd_fuera_rango = 0;
        else
            fuera_rango = Qcmd > Q_max | Qcmd < Q_min;
            tiempo_Qcmd_fuera_rango = sum( ...
                diff(t_Qcmd).*double(fuera_rango(1:end-1)));
        end
    end

    metricas.RiseTime = info.RiseTime;
    metricas.SettlingTime = info.SettlingTime;
    metricas.Overshoot = info.Overshoot;
    metricas.ErrorEstacionario = error_estacionario;
    metricas.TemperaturaMaxima = max(T1);
    metricas.PotenciaMinima = min(Q1);
    metricas.PotenciaMaxima = max(Q1);
    metricas.TiempoQcmdFueraRango = tiempo_Qcmd_fuera_rango;
end

function [t, datos] = extraerTimeseries(senal, nombre)

    if ~isa(senal, 'timeseries')
        error('%s debe estar guardada en formato Timeseries.', nombre);
    end

    t = senal.Time(:);
    datos = squeeze(senal.Data);

    if ~isvector(datos)
        error('%s debe contener una unica senal.', nombre);
    end

    datos = datos(:);

    if numel(t) ~= numel(datos)
        error('El tiempo y los datos de %s tienen longitudes distintas.', ...
            nombre);
    end
end
