ASFLAGS_ADDITIONAL = -c -g -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_LEONARDO -DARDUINO_ARCH_AVR -D_RUNONTARGETHARDWARE_BUILD_ -D_ROTH_LEONARDO_ -DUSB_VID=0x2341 -DUSB_PID=0x8036 -DUSB_MANUFACTURER=\""Unknown\"" -DUSB_PRODUCT=\""Arduino Leonardo\"" -DARDUINO_VIRTUAL_COM_PORT -DARDUINO_NUM_SERIAL_PORTS=2
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2025b/toolbox/target/SUPPOR~1/ARDUIN~2/registry/..
STACK_SIZE = 64
